-- ============================================================
-- PAYMENT LINKS MIGRATION
-- ============================================================
-- This script creates the payment_links table for tracking
-- payment links generated by admins for users to purchase credits.
--
-- Run this in the Supabase SQL Editor or via psql.
-- Safe to run multiple times (uses IF NOT EXISTS).
-- ============================================================

-- Create payment_links table
CREATE TABLE IF NOT EXISTS payment_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token TEXT NOT NULL UNIQUE,
    user_id UUID REFERENCES user_profiles(id) ON DELETE CASCADE NOT NULL,
    credit_amount INTEGER NOT NULL,
    plan_name TEXT, -- e.g., 'Starter', 'Pro', 'Enterprise', or null for custom
    description TEXT, -- Optional notes about the payment
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'completed', 'cancelled', 'expired')),
    created_by UUID REFERENCES user_profiles(id) ON DELETE SET NULL, -- Admin who created the link
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    paid_at TIMESTAMPTZ, -- When user clicked "I've Paid"
    completed_at TIMESTAMPTZ, -- When admin confirmed payment and added credits
    completed_by UUID REFERENCES user_profiles(id) ON DELETE SET NULL -- Admin who confirmed payment
);

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_payment_links_token ON payment_links(token);
CREATE INDEX IF NOT EXISTS idx_payment_links_user_id ON payment_links(user_id);
CREATE INDEX IF NOT EXISTS idx_payment_links_status ON payment_links(status);
CREATE INDEX IF NOT EXISTS idx_payment_links_created_by ON payment_links(created_by);
CREATE INDEX IF NOT EXISTS idx_payment_links_created_at ON payment_links(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_links_expires_at ON payment_links(expires_at);

-- Enable Row Level Security
ALTER TABLE payment_links ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Note: All API operations use service role which bypasses RLS
-- These policies allow users to view their own payment links for direct access

-- Users can view their own payment links
DO $$ BEGIN
  CREATE POLICY "Users can view their own payment_links"
    ON payment_links FOR SELECT
    USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Users can update their own payment links (to mark as paid)
DO $$ BEGIN
  CREATE POLICY "Users can update their own payment_links"
    ON payment_links FOR UPDATE
    USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Add comments
COMMENT ON TABLE payment_links IS 'Tracks payment links generated by admins for users to purchase credits';
COMMENT ON COLUMN payment_links.token IS 'Unique token used in the payment URL';
COMMENT ON COLUMN payment_links.user_id IS 'User who will receive credits after payment';
COMMENT ON COLUMN payment_links.credit_amount IS 'Number of credits to add after payment';
COMMENT ON COLUMN payment_links.plan_name IS 'Name of the credit plan (Starter, Pro, Enterprise, or custom)';
COMMENT ON COLUMN payment_links.description IS 'Optional notes about this payment link';
COMMENT ON COLUMN payment_links.status IS 'Status: pending, paid (user clicked I''ve Paid), completed (admin confirmed), cancelled, expired';
COMMENT ON COLUMN payment_links.created_by IS 'Admin who created this payment link';
COMMENT ON COLUMN payment_links.expires_at IS 'When this link expires and can no longer be used';
COMMENT ON COLUMN payment_links.paid_at IS 'When user indicated they have paid';
COMMENT ON COLUMN payment_links.completed_at IS 'When admin confirmed payment and credits were added';
COMMENT ON COLUMN payment_links.completed_by IS 'Admin who confirmed the payment';

-- ============================================================
-- VERIFICATION QUERIES
-- ============================================================
SELECT 'VERIFYING PAYMENT_LINKS TABLE...' AS status;
SELECT column_name, data_type, is_nullable
FROM information_schema.columns 
WHERE table_name = 'payment_links'
ORDER BY ordinal_position;

SELECT 'PAYMENT LINKS MIGRATION COMPLETE!' AS status;

