-- ============================================================
-- SCRAPE SIGNUP LINKS MIGRATION
-- ============================================================
-- This script creates the scrape_signup_links table for tracking
-- signup links generated by admins for scrape-only users.
--
-- Run this in the Supabase SQL Editor or via psql.
-- Safe to run multiple times (uses IF NOT EXISTS).
-- ============================================================

-- Create scrape_signup_links table
CREATE TABLE IF NOT EXISTS scrape_signup_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token TEXT NOT NULL UNIQUE,
    created_by UUID REFERENCES user_profiles(id) ON DELETE SET NULL, -- Admin who created the link
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ, -- When the link was used
    used_by UUID REFERENCES user_profiles(id) ON DELETE SET NULL -- User who used the link
);

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_scrape_signup_links_token ON scrape_signup_links(token);
CREATE INDEX IF NOT EXISTS idx_scrape_signup_links_created_by ON scrape_signup_links(created_by);
CREATE INDEX IF NOT EXISTS idx_scrape_signup_links_used_at ON scrape_signup_links(used_at);
CREATE INDEX IF NOT EXISTS idx_scrape_signup_links_expires_at ON scrape_signup_links(expires_at);

-- Enable Row Level Security
ALTER TABLE scrape_signup_links ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Note: All API operations use service role which bypasses RLS
-- These policies are for direct database access if needed

-- Allow service role full access (this is automatic when using service role key)
-- For regular users, access is managed through API routes that use service role

-- Add comments
COMMENT ON TABLE scrape_signup_links IS 'Tracks signup links generated by admins for scrape-only users';
COMMENT ON COLUMN scrape_signup_links.token IS 'Unique token used in the signup URL';
COMMENT ON COLUMN scrape_signup_links.created_by IS 'Admin who created this signup link';
COMMENT ON COLUMN scrape_signup_links.expires_at IS 'When this link expires and can no longer be used';
COMMENT ON COLUMN scrape_signup_links.used_at IS 'When this link was used to create an account';
COMMENT ON COLUMN scrape_signup_links.used_by IS 'User who was created using this link';

-- ============================================================
-- VERIFICATION QUERIES
-- ============================================================
SELECT 'VERIFYING SCRAPE_SIGNUP_LINKS TABLE...' AS status;
SELECT column_name, data_type, is_nullable
FROM information_schema.columns 
WHERE table_name = 'scrape_signup_links'
ORDER BY ordinal_position;

SELECT 'SCRAPE SIGNUP LINKS MIGRATION COMPLETE!' AS status;

